---
- name: Create User and Group
  block:
    - name: Create group
      group:
        name: "{{ group_name }}"
        gid: "{{ group_gid | int }}"
        state: present

    - name: Create user
      user:
        name: "{{ user_name }}"
        uid: "{{ user_uid | int }}"
        group: "{{ group_name }}"
        home: "{{ user_home }}"
        shell: /bin/bash
        state: present

- name: Install Docker and Docker-compose
  block:
    - name: Installing dependecies for docker installation
      apt:
        name: [ libffi-dev, libssl-dev, python3, python3-pip, sed, nfs-common, python3-requests, python3-docker ]
        update_cache: yes

    - name: Remove python-configparser package
      apt:
        name: python-configparser
        state: absent

    - name: Get docker install script
      get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh

    - name: Install docker
      shell: sh /tmp/get-docker.sh
      args:
        creates: /usr/bin/docker

    - name: Adding '{{ user_name }}' to the docker group
      user:
         name: '{{ user_name }}'
         groups: docker
         append: yes

    - name: Install docker-compose
      apt:
        name: [docker-compose]
        update_cache: yes

- name: Add docker network for application containers to use
  shell: "docker network inspect {{ docker_network_name }} || docker network create {{ docker_network_name }}"

- name: Create server data directories
  block:
    - name: Mount server data NFS and add docker systemd dependency
      import_role:
        name: network-file-share-mount
      vars:
        nfs_server_address: "{{ server_data_nfs_server_address }}"
        remote_dir_path: "{{ server_data_remote_dir_path }}"
        local_mount_path: "{{ server_data_local_mount_path }}"
        mount_dir_user: "{{ user_name }}"
        mount_dir_group: "{{ group_name }}"
      when: server_data_location_type == 'nfs'

    - name: Create server data LOCAL
      file:
        path: "{{ server_data_local_mount_path }}"
        state: directory
        owner: "{{ user_name }}"
        group: "{{ group_name }}"
      when: server_data_location_type == 'local'