---
# User setup
user_name: "{{ gv_local_brs_user }}"
user_uid: "{{ gv_local_brs_uid }}"
group_name: "{{ gv_local_brs_group }}"
group_gid: "{{ gv_local_brs_gid }}"
user_home: "{{ gv_local_brs_user_home }}"

# Directory setup

## Server data location type. Options : [local, nfs]
server_data_location_type: "{{ gv_storage_location_type }}"
server_data_local_mount_path: "{{ gv_server_data_root_local_mount_path }}"

### NFS config : A directory located in auto mounted NFS file system

server_data_nfs_server_address: "{{ gv_nfs_server_address }}"
server_data_remote_dir_path: "{{ gv_server_data_remote_path }}"

